version: 1.0.{build}

branches:
  only:
  - master
  - /feature*/

build_script:
- ps: .\build.ps1
test: off

artifacts:
- path: artifacts/packages/*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/spudmashmedia/api/v2/package
  api_key:
    secure: W4YjBHFnuE76HpsS3iBZ7z1oPzFVAOjNPfcCofmoF47re+9jH1R625k7VAVHIvNZ
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: 99EzZGKql3dmUwAjLi1keNAnZHTQHwxc/DUw04PX0zEmOA51looWOjoAFfJLdmtT
  on:
    branch: master
    appveyor_repo_tag: true
image: Visual Studio 2017

#install:
#  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
#  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log 

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/